const asiService = require('../services/asiService');
const Task = require('../models/Task');
const Conversation = require('../models/Conversation');
const { successResponse, errorResponse } = require('../utils/responseHandler');
const pdf = require('pdf-parse'); // For document extraction

exports.generateTasks = async (req, res, next) => {
    const { prompt } = req.body;
    
    if (!prompt || typeof prompt !== 'string') {
        return res.status(400).json({ error: 'Prompt is required and must be a string' });
    }

    console.log(`\n[LOG - TASK GENERATION]: Initiating generation for prompt: "${prompt}"`);

    try {
        console.log(`[LOG - TASK GENERATION]: Calling ASI API...`);
        const tasks = await asiService.generateTasksWorkflow(prompt);
        console.log(`[LOG - TASK GENERATION]: ASI returned ${tasks.length} tasks.`);
        

        const savedTasks = [];
        for (const t of tasks) {
            try {
                const savedTask = await Task.create({
                    title: t.title,
                    description: t.description || 'Generated by ASI-1',
                    status: 'pending'
                });
                savedTasks.push(savedTask);
            } catch (err) {
                console.warn(`[WARN - TASK GENERATION]: Failed to save task: ${t.title}`);
            }
        }
        
        console.log(`[LOG - TASK GENERATION]: Successfully synced tasks to database.`);
        return res.status(200).json({ success: true, tasks: savedTasks });
    } catch (error) {
        console.error(`[ERROR - TASK GENERATION]:`, error);
        next(error);
    }
};

exports.analyzeDocument = async (req, res, next) => {
    if (!req.file && !req.body.text) {
        return res.status(400).json({ error: 'No document file or text provided' });
    }

    console.log(`\n[LOG - DOC ANALYSIS]: Initiating document analysis...`);

    try {
        let text = req.body.text || '';

        if (req.file) {
            if (req.file.mimetype === 'application/pdf') {
                try {
                    const parser = new pdf.PDFParse({ data: req.file.buffer });
                    const data = await parser.getText();
                    text = data.text;
                } catch (pdfError) {
                    console.warn('[WARN - DOC ANALYSIS]: PDF parse failed, using raw buffer text.');
                    text = req.file.buffer.toString('utf-8').replace(/[^\x20-\x7E\n]/g, ' ');
                }
            } else {
                text = req.file.buffer.toString('utf-8');
            }
        }

        console.log(`[LOG - DOC ANALYSIS]: Extracted ${text.length} characters. Calling ASI API...`);
        
        const result = await asiService.analyzeDocumentWorkflow(text);
        
        console.log(`[LOG - DOC ANALYSIS]: Analysis completed successfully.`);
        return res.status(200).json({
            success: true,
            summary: result.summary,
            insights: result.insights,
            filename: req.file ? req.file.originalname : 'raw_text_input',
        });
    } catch (error) {
        console.error('[ERROR - DOC ANALYSIS]:', error);
        next(error);
    }
};

exports.executeWorkflow = async (req, res, next) => {
    const { taskList, prompt } = req.body;
    const command = prompt || (taskList ? taskList.map(t => t.title).join(', ') : '');

    if (!command) {
        return res.status(400).json({ error: 'Command or taskList is required' });
    }

    console.log(`\n[LOG - WORKFLOW]: Starting workflow execution for command: "${command}"`);

    try {
        console.log(`[LOG - WORKFLOW]: Detecting user intent with ASI API...`);
        const intents = await asiService.detectIntent(command);
        console.log(`[LOG - WORKFLOW]: Detected intents: ${intents.join(', ')}`);

        const logs = [
            { message: "Workflow initialized", status: "success", timestamp: new Date() },
            { message: `Intents detected: ${intents.join(', ')}`, status: "success", timestamp: new Date() }
        ];

        let finalResult = {
            reply: "",
            workflowExecuted: intents,
            tasks: [],
            logs: logs
        };

        for (const intent of intents) {
            console.log(`[LOG - WORKFLOW]: Executing step -> ${intent}`);
            logs.push({ message: `Executing step: ${intent}`, status: "success", timestamp: new Date() });

            if (intent === 'task_generation') {
                const generatedTasks = await asiService.generateTasksWorkflow(command);
                if (generatedTasks && generatedTasks.length > 0) {
                    finalResult.reply += `\nI have extracted the following ${generatedTasks.length} task(s):\n` + generatedTasks.map((t, i) => `${i + 1}. **${t.title}**: ${t.description}`).join('\n');
                } else {
                    finalResult.reply += `\nI could not find any explicit tasks to extract from your prompt.`;
                }
                for (const t of generatedTasks) {
                    try {
                        const savedTask = await Task.create({
                            title: t.title,
                            description: t.description || 'Generated by ASI-1',
                            status: 'pending'
                        });
                        finalResult.tasks.push(savedTask);
                    } catch (err) {
                        console.warn(`[WARN - WORKFLOW]: Failed to save task: ${t.title}`);
                        finalResult.tasks.push(t);
                    }
                }
            } 
            else if (intent === 'summarization') {
                const analysis = await asiService.analyzeDocumentWorkflow(command);
                finalResult.reply += `\n- Summary generated.`;
            }
            else {
                const reply = await asiService.executeGenericPrompt(command);
                finalResult.reply += `\n${reply}`;
            }
        }

        console.log(`[LOG - WORKFLOW]: Workflow completed successfully.`);
        logs.push({ message: "Workflow finished processing", status: "success", timestamp: new Date() });

        return res.status(200).json(finalResult);
    } catch (error) {
        console.error('[LOG - WORKFLOW ERROR]:', error);
        next(error);
    }
};


exports.getTasks = async (req, res, next) => {
    try {
        const tasks = await Task.find().sort({ createdAt: -1 });
        return successResponse(res, tasks);
    } catch (error) {
        next(error);
    }
};

exports.createTask = async (req, res, next) => {
    const { title } = req.body;
    if (!title || typeof title !== 'string' || !title.trim()) {
        return errorResponse(res, 'Task title is required', 400);
    }
    try {
        const task = await Task.create({ title: title.trim(), description: req.body.description || '', status: 'pending' });
        return successResponse(res, task, 201);
    } catch (error) {
        next(error);
    }
};

exports.toggleTaskStatus = async (req, res, next) => {
    const { id } = req.params;
    try {
        const task = await Task.findById(id);
        if (!task) return errorResponse(res, 'Task not found', 404);

        task.status = task.status === 'completed' ? 'pending' : 'completed';
        await task.save();
        return successResponse(res, task);
    } catch (error) {
        next(error);
    }
};

exports.getHistory = async (req, res, next) => {
    const userId = req.user?.id || 'demo-user';
    try {
        const history = await Conversation.find({ userId }).sort({ timestamp: 1 }).limit(50);
        return successResponse(res, history);
    } catch (error) {
        next(error);
    }
};

exports.deleteTask = async (req, res, next) => {
    const { id } = req.params;
    try {
        const task = await Task.findByIdAndDelete(id);
        if (!task) return errorResponse(res, 'Task not found', 404);
        return successResponse(res, { message: 'Task deleted successfully' });
    } catch (error) {
        next(error);
    }
};
